spring.application.name=springboot-restful-webservices
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=user_management
spring.datasource.password=user

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.open-in-view=false
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
